import { useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { createIdempotencyKey, mealApi } from '@/lib/meal-api';
import { useMealsStore } from '@/store/use-meals-store';
import { validateSelectedMealImage } from '@/lib/meal-validation';
import type { MealAnalysis, MealType, SelectedMealImage } from '@/types/meals';

const colors = { canvas: '#FFF9F0', surface: '#FFFFFF', ink: '#2F3542', slate: '#697386', apricot: '#FF9E7A', peach: '#FFF0E7', leaf: '#EAF0ED', border: '#E9E1D8', coral: '#FF8B78' };

export default function AiMealScreen() {
  const params = useLocalSearchParams<{ date?: string }>();
  const [image, setImage] = useState<SelectedMealImage | null>(null);
  const [analysis, setAnalysis] = useState<MealAnalysis | null>(null);
  const [accepted, setAccepted] = useState(false);
  const [busy, setBusy] = useState(false);
  const appendMeal = useMealsStore((state) => state.appendMeal);
  const pick = async (mode: 'camera' | 'library') => {
    const permission = mode === 'camera' ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) { Alert.alert('Cần quyền truy cập', mode === 'camera' ? 'Cho phép camera để chụp món ăn.' : 'Cho phép thư viện ảnh để chọn món ăn.'); return; }
    const result = mode === 'camera' ? await ImagePicker.launchCameraAsync({ quality: 0.82, allowsEditing: true, aspect: [4, 3] }) : await ImagePicker.launchImageLibraryAsync({ quality: 0.82, allowsEditing: true, aspect: [4, 3] });
    if (result.canceled || !result.assets[0]) return;
    const asset = result.assets[0];
    const selected: SelectedMealImage = { uri: asset.uri, fileName: asset.fileName ?? null, mimeType: asset.mimeType ?? null, fileSize: asset.fileSize ?? null };
    const validation = validateSelectedMealImage(selected);
    if (Object.keys(validation).length > 0) { Alert.alert('Ảnh chưa phù hợp', validation.fileSize ?? validation.mimeType ?? 'Vui lòng thử ảnh khác.'); return; }
    setImage(selected);
  };
  const analyze = async () => { if (!image || busy) return; setBusy(true); const response = await mealApi.createAnalysis({ image, mealType: 'DINNER' as MealType, eatenAt: new Date(`${params.date ?? new Date().toISOString().slice(0, 10)}T19:00:00`).toISOString() }, createIdempotencyKey()); setAnalysis(response.data); setBusy(false); };
  const confirm = async () => { if (!analysis || !accepted || busy) return; setBusy(true); const response = await mealApi.confirmAnalysis(analysis.analysisId, createIdempotencyKey()); if (response.data) { appendMeal(response.data.meal); router.back(); } else Alert.alert('Chưa ghi lại được', response.error?.message ?? 'Bạn thử lại nhé.'); setBusy(false); };

  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.title}>Nhận diện món ăn</Text><View style={styles.spacer} /></View><Text style={styles.subtitle}>AURALE sẽ gợi ý món và thành phần. Bạn luôn được xem lại trước khi ghi.</Text>
    {!image ? <><View style={styles.permissionCard}><Text style={styles.permissionTitle}>Chọn một ảnh món ăn</Text><Text style={styles.muted}>Ảnh chỉ dùng cho phiên nhận diện này trong bản thử nghiệm.</Text><View style={styles.choiceRow}><Pressable onPress={() => void pick('camera')} style={styles.choice}><Text style={styles.choiceIcon}>＋</Text><Text style={styles.choiceTitle}>Mở camera</Text><Text style={styles.choiceCaption}>Chụp món vừa ăn</Text></Pressable><Pressable onPress={() => void pick('library')} style={styles.choice}><Text style={styles.choiceIcon}>□</Text><Text style={styles.choiceTitle}>Chọn từ máy</Text><Text style={styles.choiceCaption}>JPG, PNG hoặc WebP</Text></Pressable></View></View></> : <><View style={styles.previewCard}><Image source={{ uri: image.uri }} style={styles.preview} /><Pressable onPress={() => setImage(null)} style={styles.change}><Text style={styles.changeText}>Chọn ảnh khác</Text></Pressable></View>{!analysis ? <Pressable onPress={() => void analyze()} style={styles.primary}><Text style={styles.primaryText}>{busy ? 'Đang nhận diện…' : 'Nhận diện món ăn'}</Text></Pressable> : <View style={styles.reviewCard}><View style={styles.reviewHeader}><Text style={styles.reviewTitle}>Kiểm tra gợi ý</Text><Text style={styles.reviewBadge}>CẦN XÁC NHẬN</Text></View><Text style={styles.muted}>Hãy kiểm tra tên món, khẩu phần và các chỉ số trước khi ghi.</Text>{analysis.items.map((item) => <View key={item.analysisItemId} style={styles.item}><View style={styles.itemTop}><Text style={styles.itemName}>{item.mappedFood?.name ?? item.detectedName}</Text><Text style={styles.confidence}>{Math.round(item.confidence * 100)}%</Text></View><Text style={styles.itemMeta}>{item.servingName ?? '1 khẩu phần'} · {Math.round(item.nutrition?.caloriesKcal ?? 0)} kcal</Text></View>)}<Pressable onPress={() => setAccepted((value) => !value)} style={styles.checkRow}><View style={[styles.checkbox, accepted && styles.checkboxChecked]}>{accepted && <Text style={styles.check}>✓</Text>}</View><Text style={styles.checkText}>Tôi đã kiểm tra các gợi ý dinh dưỡng</Text></Pressable><Pressable onPress={() => void confirm()} disabled={!accepted || busy} style={[styles.primary, (!accepted || busy) && styles.disabled]}><Text style={styles.primaryText}>{busy ? 'Đang ghi lại…' : 'Xác nhận và ghi lại'}</Text></Pressable></View>}</>}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, content: { padding: 22, paddingBottom: 40 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, backText: { color: colors.ink, fontSize: 34, lineHeight: 36, marginTop: -4 }, title: { color: colors.ink, fontSize: 23, fontWeight: '700' }, spacer: { width: 44 }, subtitle: { color: colors.slate, fontSize: 15, lineHeight: 22, marginTop: 12, marginBottom: 20 }, permissionCard: { backgroundColor: colors.surface, borderRadius: 22, padding: 20 }, permissionTitle: { color: colors.ink, fontSize: 19, fontWeight: '700' }, muted: { color: colors.slate, fontSize: 14, lineHeight: 21, marginTop: 6 }, choiceRow: { flexDirection: 'row', gap: 12, marginTop: 20 }, choice: { flex: 1, backgroundColor: colors.peach, borderRadius: 18, padding: 16, minHeight: 132 }, choiceIcon: { color: colors.ink, fontSize: 30, fontWeight: '300' }, choiceTitle: { color: colors.ink, fontSize: 16, fontWeight: '700', marginTop: 8 }, choiceCaption: { color: colors.slate, fontSize: 13, marginTop: 4 }, previewCard: { backgroundColor: colors.surface, borderRadius: 22, padding: 12 }, preview: { width: '100%', height: 250, borderRadius: 16, backgroundColor: colors.leaf }, change: { alignItems: 'center', paddingTop: 12 }, changeText: { color: colors.ink, fontSize: 15, fontWeight: '700' }, primary: { minHeight: 54, borderRadius: 17, backgroundColor: colors.apricot, alignItems: 'center', justifyContent: 'center', marginTop: 16 }, primaryText: { color: colors.ink, fontSize: 16, fontWeight: '700' }, reviewCard: { backgroundColor: colors.surface, borderRadius: 22, padding: 20, marginTop: 16 }, reviewHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, reviewTitle: { color: colors.ink, fontSize: 20, fontWeight: '700' }, reviewBadge: { color: colors.ink, backgroundColor: colors.leaf, borderRadius: 9, paddingHorizontal: 8, paddingVertical: 5, fontSize: 10, fontWeight: '700' }, item: { borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: 14 }, itemTop: { flexDirection: 'row', justifyContent: 'space-between' }, itemName: { color: colors.ink, fontSize: 16, fontWeight: '700' }, confidence: { color: colors.slate, fontSize: 13 }, itemMeta: { color: colors.slate, fontSize: 14, marginTop: 5 }, checkRow: { flexDirection: 'row', alignItems: 'center', marginTop: 18, minHeight: 44 }, checkbox: { width: 24, height: 24, borderWidth: 1.5, borderColor: colors.slate, borderRadius: 7, marginRight: 10, alignItems: 'center', justifyContent: 'center' }, checkboxChecked: { backgroundColor: colors.apricot, borderColor: colors.apricot }, check: { color: colors.ink, fontWeight: '800' }, checkText: { color: colors.ink, fontSize: 14, flex: 1 }, disabled: { opacity: 0.5 } });
